name: astro
services:
  cdn-edge:
    image: nginx:alpine
    container_name: cdn-edge
    ports:
      - "8080:80"
    volumes:
      - ./dist/client:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
